// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv6FA9_HSYEhE1FOaiuAYOcl8_8M-Uv9g',
    appId: '1:208390578484:web:95520262ef03a30c7d0561',
    messagingSenderId: '208390578484',
    projectId: 'puni-ranking',
    authDomain: 'puni-ranking.firebaseapp.com',
    storageBucket: 'puni-ranking.firebasestorage.app',
    measurementId: 'G-PPMQ4MFRSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtbk71iIU5RylGIgnVKg2hUsWirUaAxf8',
    appId: '1:208390578484:android:a4a8a679119951aa7d0561',
    messagingSenderId: '208390578484',
    projectId: 'puni-ranking',
    storageBucket: 'puni-ranking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8kDBKCb2Ud-ZtwRD4oLokmJbGj5uO5BI',
    appId: '1:208390578484:ios:14d6ef2c55c9df137d0561',
    messagingSenderId: '208390578484',
    projectId: 'puni-ranking',
    storageBucket: 'puni-ranking.firebasestorage.app',
    iosBundleId: 'com.puni.app.puniProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8kDBKCb2Ud-ZtwRD4oLokmJbGj5uO5BI',
    appId: '1:208390578484:ios:14d6ef2c55c9df137d0561',
    messagingSenderId: '208390578484',
    projectId: 'puni-ranking',
    storageBucket: 'puni-ranking.firebasestorage.app',
    iosBundleId: 'com.puni.app.puniProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv6FA9_HSYEhE1FOaiuAYOcl8_8M-Uv9g',
    appId: '1:208390578484:web:6f2e2671653ace597d0561',
    messagingSenderId: '208390578484',
    projectId: 'puni-ranking',
    authDomain: 'puni-ranking.firebaseapp.com',
    storageBucket: 'puni-ranking.firebasestorage.app',
    measurementId: 'G-ESSGJ1L4Q9',
  );
}
